const all = [
  'Toutes caractéristiques',
  'Bureau',
  'Jacuzzi intérieur',
  'Salle de bain par chambre',
  'Haut-débit internet',
  'Système alarme',
  'Salle de Gym',
  'Salle de jeux',
  "Salle d'atelier",
  'Lave-vaisselle',
  'Plancher',
  'Penderie',
  'Balcon',
  'Piscine',
  'Spa extérieur',
  'Cuisine extérieure',
  'Court de sport',
  'Espace extérieur',
  'Hangar',
  'Entièrement clôturé',
  'Parking',
  'Climatisation',
  'Chauffage',
  'Haute efficacité énergétique',
  "Réservoir d'eau",
  'Panneaux solaires',
  'Eau chaude solaire',
]

export { all }
